// Code generated by protoc-gen-go-bbs. DO NOT EDIT.
// versions:
// - protoc-gen-go-bbs v0.0.1
// - protoc            v5.26.1
// source: certificate_properties.proto

package models

// Prevent copylock errors when using ProtoCertificateProperties directly
type CertificateProperties struct {
	OrganizationalUnit []string
}

func (this *CertificateProperties) Equal(that interface{}) bool {

	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CertificateProperties)
	if !ok {
		that2, ok := that.(CertificateProperties)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}

	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}

	if len(this.OrganizationalUnit) != len(that1.OrganizationalUnit) {
		return false
	}
	for i := range this.OrganizationalUnit {
		if this.OrganizationalUnit[i] != that1.OrganizationalUnit[i] {
			return false
		}
	}
	return true
}
func (m *CertificateProperties) GetOrganizationalUnit() []string {
	if m != nil {
		return m.OrganizationalUnit
	}
	return nil
}
func (m *CertificateProperties) SetOrganizationalUnit(value []string) {
	if m != nil {
		m.OrganizationalUnit = value
	}
}
func (x *CertificateProperties) ToProto() *ProtoCertificateProperties {
	proto := &ProtoCertificateProperties{
		OrganizationalUnit: x.OrganizationalUnit,
	}
	return proto
}

func (x *ProtoCertificateProperties) FromProto() *CertificateProperties {
	copysafe := &CertificateProperties{
		OrganizationalUnit: x.OrganizationalUnit,
	}
	return copysafe
}

func CertificatePropertiesToProtoSlice(values []*CertificateProperties) []*ProtoCertificateProperties {
	result := make([]*ProtoCertificateProperties, len(values))
	for i, val := range values {
		result[i] = val.ToProto()
	}
	return result
}

func CertificatePropertiesFromProtoSlice(values []*ProtoCertificateProperties) []*CertificateProperties {
	result := make([]*CertificateProperties, len(values))
	for i, val := range values {
		result[i] = val.FromProto()
	}
	return result
}
