// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: desired_lrp_requests.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DesiredLRPLifecycleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DesiredLRPLifecycleResponse) Reset() {
	*x = DesiredLRPLifecycleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesiredLRPLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredLRPLifecycleResponse) ProtoMessage() {}

func (x *DesiredLRPLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredLRPLifecycleResponse.ProtoReflect.Descriptor instead.
func (*DesiredLRPLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{0}
}

func (x *DesiredLRPLifecycleResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DesiredLRPsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error       *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	DesiredLrps []*DesiredLRP `protobuf:"bytes,2,rep,name=desired_lrps,json=desiredLrps,proto3" json:"desired_lrps,omitempty"`
}

func (x *DesiredLRPsResponse) Reset() {
	*x = DesiredLRPsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesiredLRPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredLRPsResponse) ProtoMessage() {}

func (x *DesiredLRPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredLRPsResponse.ProtoReflect.Descriptor instead.
func (*DesiredLRPsResponse) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{1}
}

func (x *DesiredLRPsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DesiredLRPsResponse) GetDesiredLrps() []*DesiredLRP {
	if x != nil {
		return x.DesiredLrps
	}
	return nil
}

type DesiredLRPsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain       string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ProcessGuids []string `protobuf:"bytes,2,rep,name=process_guids,json=processGuids,proto3" json:"process_guids,omitempty"`
}

func (x *DesiredLRPsRequest) Reset() {
	*x = DesiredLRPsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesiredLRPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredLRPsRequest) ProtoMessage() {}

func (x *DesiredLRPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredLRPsRequest.ProtoReflect.Descriptor instead.
func (*DesiredLRPsRequest) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{2}
}

func (x *DesiredLRPsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DesiredLRPsRequest) GetProcessGuids() []string {
	if x != nil {
		return x.ProcessGuids
	}
	return nil
}

type DesiredLRPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error      *Error      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	DesiredLrp *DesiredLRP `protobuf:"bytes,2,opt,name=desired_lrp,json=desiredLrp,proto3" json:"desired_lrp,omitempty"`
}

func (x *DesiredLRPResponse) Reset() {
	*x = DesiredLRPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesiredLRPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredLRPResponse) ProtoMessage() {}

func (x *DesiredLRPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredLRPResponse.ProtoReflect.Descriptor instead.
func (*DesiredLRPResponse) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{3}
}

func (x *DesiredLRPResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DesiredLRPResponse) GetDesiredLrp() *DesiredLRP {
	if x != nil {
		return x.DesiredLrp
	}
	return nil
}

type DesiredLRPSchedulingInfosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                     *Error                      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	DesiredLrpSchedulingInfos []*DesiredLRPSchedulingInfo `protobuf:"bytes,2,rep,name=desired_lrp_scheduling_infos,json=desiredLrpSchedulingInfos,proto3" json:"desired_lrp_scheduling_infos,omitempty"`
}

func (x *DesiredLRPSchedulingInfosResponse) Reset() {
	*x = DesiredLRPSchedulingInfosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesiredLRPSchedulingInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredLRPSchedulingInfosResponse) ProtoMessage() {}

func (x *DesiredLRPSchedulingInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredLRPSchedulingInfosResponse.ProtoReflect.Descriptor instead.
func (*DesiredLRPSchedulingInfosResponse) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{4}
}

func (x *DesiredLRPSchedulingInfosResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DesiredLRPSchedulingInfosResponse) GetDesiredLrpSchedulingInfos() []*DesiredLRPSchedulingInfo {
	if x != nil {
		return x.DesiredLrpSchedulingInfos
	}
	return nil
}

type DesiredLRPSchedulingInfoByProcessGuidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                    *Error                    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	DesiredLrpSchedulingInfo *DesiredLRPSchedulingInfo `protobuf:"bytes,2,opt,name=desired_lrp_scheduling_info,json=desiredLrpSchedulingInfo,proto3" json:"desired_lrp_scheduling_info,omitempty"`
}

func (x *DesiredLRPSchedulingInfoByProcessGuidResponse) Reset() {
	*x = DesiredLRPSchedulingInfoByProcessGuidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesiredLRPSchedulingInfoByProcessGuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredLRPSchedulingInfoByProcessGuidResponse) ProtoMessage() {}

func (x *DesiredLRPSchedulingInfoByProcessGuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredLRPSchedulingInfoByProcessGuidResponse.ProtoReflect.Descriptor instead.
func (*DesiredLRPSchedulingInfoByProcessGuidResponse) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{5}
}

func (x *DesiredLRPSchedulingInfoByProcessGuidResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DesiredLRPSchedulingInfoByProcessGuidResponse) GetDesiredLrpSchedulingInfo() *DesiredLRPSchedulingInfo {
	if x != nil {
		return x.DesiredLrpSchedulingInfo
	}
	return nil
}

type DesiredLRPByProcessGuidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessGuid string `protobuf:"bytes,1,opt,name=process_guid,proto3" json:"process_guid,omitempty"`
}

func (x *DesiredLRPByProcessGuidRequest) Reset() {
	*x = DesiredLRPByProcessGuidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesiredLRPByProcessGuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredLRPByProcessGuidRequest) ProtoMessage() {}

func (x *DesiredLRPByProcessGuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredLRPByProcessGuidRequest.ProtoReflect.Descriptor instead.
func (*DesiredLRPByProcessGuidRequest) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{6}
}

func (x *DesiredLRPByProcessGuidRequest) GetProcessGuid() string {
	if x != nil {
		return x.ProcessGuid
	}
	return ""
}

type DesireLRPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesiredLrp *DesiredLRP `protobuf:"bytes,1,opt,name=desired_lrp,json=desiredLrp,proto3" json:"desired_lrp,omitempty"`
}

func (x *DesireLRPRequest) Reset() {
	*x = DesireLRPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesireLRPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesireLRPRequest) ProtoMessage() {}

func (x *DesireLRPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesireLRPRequest.ProtoReflect.Descriptor instead.
func (*DesireLRPRequest) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{7}
}

func (x *DesireLRPRequest) GetDesiredLrp() *DesiredLRP {
	if x != nil {
		return x.DesiredLrp
	}
	return nil
}

type UpdateDesiredLRPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessGuid string            `protobuf:"bytes,1,opt,name=process_guid,proto3" json:"process_guid,omitempty"`
	Update      *DesiredLRPUpdate `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *UpdateDesiredLRPRequest) Reset() {
	*x = UpdateDesiredLRPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDesiredLRPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDesiredLRPRequest) ProtoMessage() {}

func (x *UpdateDesiredLRPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDesiredLRPRequest.ProtoReflect.Descriptor instead.
func (*UpdateDesiredLRPRequest) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDesiredLRPRequest) GetProcessGuid() string {
	if x != nil {
		return x.ProcessGuid
	}
	return ""
}

func (x *UpdateDesiredLRPRequest) GetUpdate() *DesiredLRPUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type RemoveDesiredLRPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessGuid string `protobuf:"bytes,1,opt,name=process_guid,proto3" json:"process_guid,omitempty"`
}

func (x *RemoveDesiredLRPRequest) Reset() {
	*x = RemoveDesiredLRPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_desired_lrp_requests_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDesiredLRPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDesiredLRPRequest) ProtoMessage() {}

func (x *RemoveDesiredLRPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desired_lrp_requests_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDesiredLRPRequest.ProtoReflect.Descriptor instead.
func (*RemoveDesiredLRPRequest) Descriptor() ([]byte, []int) {
	return file_desired_lrp_requests_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveDesiredLRPRequest) GetProcessGuid() string {
	if x != nil {
		return x.ProcessGuid
	}
	return ""
}

var File_desired_lrp_requests_proto protoreflect.FileDescriptor

var file_desired_lrp_requests_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x72, 0x70, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x1a, 0x11, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x72,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x1b, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c,
	0x52, 0x50, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x71, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x69,
	0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x5f,
	0x6c, 0x72, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x72, 0x70, 0x73, 0x22, 0x51, 0x0a, 0x12, 0x44,
	0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x47, 0x75, 0x69, 0x64, 0x73, 0x22, 0x6e,
	0x0a, 0x12, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x69, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x72, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c,
	0x52, 0x50, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x72, 0x70, 0x22, 0xab,
	0x01, 0x0a, 0x21, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x61, 0x0a, 0x1c, 0x64, 0x65, 0x73,
	0x69, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x72, 0x70, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64,
	0x4c, 0x52, 0x50, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x19, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x72, 0x70, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0xb5, 0x01, 0x0a,
	0x2d, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x47, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x5f, 0x0a, 0x1b, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x6c,
	0x72, 0x70, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x18, 0x64, 0x65, 0x73, 0x69,
	0x72, 0x65, 0x64, 0x4c, 0x72, 0x70, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x44, 0x0a, 0x1e, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c,
	0x52, 0x50, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x47, 0x75, 0x69, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x10, 0x44, 0x65,
	0x73, 0x69, 0x72, 0x65, 0x4c, 0x52, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x72, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x73,
	0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64,
	0x4c, 0x72, 0x70, 0x22, 0x6f, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x73,
	0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x75,
	0x69, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x73, 0x69,
	0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x22, 0x3d, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65,
	0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x52, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67,
	0x75, 0x69, 0x64, 0x42, 0x22, 0x5a, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x72, 0x79, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x62, 0x62, 0x73,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_desired_lrp_requests_proto_rawDescOnce sync.Once
	file_desired_lrp_requests_proto_rawDescData = file_desired_lrp_requests_proto_rawDesc
)

func file_desired_lrp_requests_proto_rawDescGZIP() []byte {
	file_desired_lrp_requests_proto_rawDescOnce.Do(func() {
		file_desired_lrp_requests_proto_rawDescData = protoimpl.X.CompressGZIP(file_desired_lrp_requests_proto_rawDescData)
	})
	return file_desired_lrp_requests_proto_rawDescData
}

var file_desired_lrp_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_desired_lrp_requests_proto_goTypes = []interface{}{
	(*DesiredLRPLifecycleResponse)(nil),                   // 0: models.DesiredLRPLifecycleResponse
	(*DesiredLRPsResponse)(nil),                           // 1: models.DesiredLRPsResponse
	(*DesiredLRPsRequest)(nil),                            // 2: models.DesiredLRPsRequest
	(*DesiredLRPResponse)(nil),                            // 3: models.DesiredLRPResponse
	(*DesiredLRPSchedulingInfosResponse)(nil),             // 4: models.DesiredLRPSchedulingInfosResponse
	(*DesiredLRPSchedulingInfoByProcessGuidResponse)(nil), // 5: models.DesiredLRPSchedulingInfoByProcessGuidResponse
	(*DesiredLRPByProcessGuidRequest)(nil),                // 6: models.DesiredLRPByProcessGuidRequest
	(*DesireLRPRequest)(nil),                              // 7: models.DesireLRPRequest
	(*UpdateDesiredLRPRequest)(nil),                       // 8: models.UpdateDesiredLRPRequest
	(*RemoveDesiredLRPRequest)(nil),                       // 9: models.RemoveDesiredLRPRequest
	(*Error)(nil),                                         // 10: models.Error
	(*DesiredLRP)(nil),                                    // 11: models.DesiredLRP
	(*DesiredLRPSchedulingInfo)(nil),                      // 12: models.DesiredLRPSchedulingInfo
	(*DesiredLRPUpdate)(nil),                              // 13: models.DesiredLRPUpdate
}
var file_desired_lrp_requests_proto_depIdxs = []int32{
	10, // 0: models.DesiredLRPLifecycleResponse.error:type_name -> models.Error
	10, // 1: models.DesiredLRPsResponse.error:type_name -> models.Error
	11, // 2: models.DesiredLRPsResponse.desired_lrps:type_name -> models.DesiredLRP
	10, // 3: models.DesiredLRPResponse.error:type_name -> models.Error
	11, // 4: models.DesiredLRPResponse.desired_lrp:type_name -> models.DesiredLRP
	10, // 5: models.DesiredLRPSchedulingInfosResponse.error:type_name -> models.Error
	12, // 6: models.DesiredLRPSchedulingInfosResponse.desired_lrp_scheduling_infos:type_name -> models.DesiredLRPSchedulingInfo
	10, // 7: models.DesiredLRPSchedulingInfoByProcessGuidResponse.error:type_name -> models.Error
	12, // 8: models.DesiredLRPSchedulingInfoByProcessGuidResponse.desired_lrp_scheduling_info:type_name -> models.DesiredLRPSchedulingInfo
	11, // 9: models.DesireLRPRequest.desired_lrp:type_name -> models.DesiredLRP
	13, // 10: models.UpdateDesiredLRPRequest.update:type_name -> models.DesiredLRPUpdate
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_desired_lrp_requests_proto_init() }
func file_desired_lrp_requests_proto_init() {
	if File_desired_lrp_requests_proto != nil {
		return
	}
	file_desired_lrp_proto_init()
	file_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_desired_lrp_requests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesiredLRPLifecycleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesiredLRPsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesiredLRPsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesiredLRPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesiredLRPSchedulingInfosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesiredLRPSchedulingInfoByProcessGuidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesiredLRPByProcessGuidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesireLRPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDesiredLRPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_desired_lrp_requests_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveDesiredLRPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_desired_lrp_requests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_desired_lrp_requests_proto_goTypes,
		DependencyIndexes: file_desired_lrp_requests_proto_depIdxs,
		MessageInfos:      file_desired_lrp_requests_proto_msgTypes,
	}.Build()
	File_desired_lrp_requests_proto = out.File
	file_desired_lrp_requests_proto_rawDesc = nil
	file_desired_lrp_requests_proto_goTypes = nil
	file_desired_lrp_requests_proto_depIdxs = nil
}
