// Code generated by protoc-gen-gogo.
// source: volume_mount.proto
// DO NOT EDIT!

package models

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strconv "strconv"

import bytes "bytes"

import strings "strings"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
import sort "sort"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DeprecatedBindMountMode int32

const (
	DeprecatedBindMountMode_RO DeprecatedBindMountMode = 0
	DeprecatedBindMountMode_RW DeprecatedBindMountMode = 1
)

var DeprecatedBindMountMode_name = map[int32]string{
	0: "RO",
	1: "RW",
}
var DeprecatedBindMountMode_value = map[string]int32{
	"RO": 0,
	"RW": 1,
}

func (x DeprecatedBindMountMode) Enum() *DeprecatedBindMountMode {
	p := new(DeprecatedBindMountMode)
	*p = x
	return p
}
func (x DeprecatedBindMountMode) MarshalJSON() ([]byte, error) {
	return proto.MarshalJSONEnum(DeprecatedBindMountMode_name, int32(x))
}
func (x *DeprecatedBindMountMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DeprecatedBindMountMode_value, data, "DeprecatedBindMountMode")
	if err != nil {
		return err
	}
	*x = DeprecatedBindMountMode(value)
	return nil
}
func (DeprecatedBindMountMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorVolumeMount, []int{0}
}

type SharedDevice struct {
	VolumeId    string `protobuf:"bytes,1,req,name=volume_id,json=volumeId" json:"volume_id"`
	MountConfig string `protobuf:"bytes,2,opt,name=mount_config,json=mountConfig" json:"mount_config"`
}

func (m *SharedDevice) Reset()                    { *m = SharedDevice{} }
func (*SharedDevice) ProtoMessage()               {}
func (*SharedDevice) Descriptor() ([]byte, []int) { return fileDescriptorVolumeMount, []int{0} }

func (m *SharedDevice) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

func (m *SharedDevice) GetMountConfig() string {
	if m != nil {
		return m.MountConfig
	}
	return ""
}

type VolumeMount struct {
	DeprecatedVolumeId string                  `protobuf:"bytes,2,opt,name=deprecated_volume_id,json=deprecatedVolumeId" json:"deprecated_volume_id"`
	DeprecatedMode     DeprecatedBindMountMode `protobuf:"varint,4,opt,name=deprecated_mode,json=deprecatedMode,enum=models.DeprecatedBindMountMode" json:"deprecated_mode"`
	DeprecatedConfig   []byte                  `protobuf:"bytes,5,opt,name=deprecated_config,json=deprecatedConfig" json:"deprecated_config"`
	Driver             string                  `protobuf:"bytes,1,opt,name=driver" json:"driver"`
	ContainerDir       string                  `protobuf:"bytes,3,opt,name=container_dir,json=containerDir" json:"container_dir"`
	Mode               string                  `protobuf:"bytes,6,opt,name=mode" json:"mode"`
	Shared             *SharedDevice           `protobuf:"bytes,7,opt,name=shared" json:"shared,omitempty"`
}

func (m *VolumeMount) Reset()                    { *m = VolumeMount{} }
func (*VolumeMount) ProtoMessage()               {}
func (*VolumeMount) Descriptor() ([]byte, []int) { return fileDescriptorVolumeMount, []int{1} }

func (m *VolumeMount) GetDeprecatedVolumeId() string {
	if m != nil {
		return m.DeprecatedVolumeId
	}
	return ""
}

func (m *VolumeMount) GetDeprecatedMode() DeprecatedBindMountMode {
	if m != nil {
		return m.DeprecatedMode
	}
	return DeprecatedBindMountMode_RO
}

func (m *VolumeMount) GetDeprecatedConfig() []byte {
	if m != nil {
		return m.DeprecatedConfig
	}
	return nil
}

func (m *VolumeMount) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *VolumeMount) GetContainerDir() string {
	if m != nil {
		return m.ContainerDir
	}
	return ""
}

func (m *VolumeMount) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *VolumeMount) GetShared() *SharedDevice {
	if m != nil {
		return m.Shared
	}
	return nil
}

type VolumePlacement struct {
	DriverNames []string `protobuf:"bytes,1,rep,name=driver_names,json=driverNames" json:"driver_names"`
}

func (m *VolumePlacement) Reset()                    { *m = VolumePlacement{} }
func (*VolumePlacement) ProtoMessage()               {}
func (*VolumePlacement) Descriptor() ([]byte, []int) { return fileDescriptorVolumeMount, []int{2} }

func (m *VolumePlacement) GetDriverNames() []string {
	if m != nil {
		return m.DriverNames
	}
	return nil
}

func init() {
	proto.RegisterType((*SharedDevice)(nil), "models.SharedDevice")
	proto.RegisterType((*VolumeMount)(nil), "models.VolumeMount")
	proto.RegisterType((*VolumePlacement)(nil), "models.VolumePlacement")
	proto.RegisterEnum("models.DeprecatedBindMountMode", DeprecatedBindMountMode_name, DeprecatedBindMountMode_value)
}
func (x DeprecatedBindMountMode) String() string {
	s, ok := DeprecatedBindMountMode_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *SharedDevice) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SharedDevice)
	if !ok {
		that2, ok := that.(SharedDevice)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.VolumeId != that1.VolumeId {
		return false
	}
	if this.MountConfig != that1.MountConfig {
		return false
	}
	return true
}
func (this *VolumeMount) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*VolumeMount)
	if !ok {
		that2, ok := that.(VolumeMount)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.DeprecatedVolumeId != that1.DeprecatedVolumeId {
		return false
	}
	if this.DeprecatedMode != that1.DeprecatedMode {
		return false
	}
	if !bytes.Equal(this.DeprecatedConfig, that1.DeprecatedConfig) {
		return false
	}
	if this.Driver != that1.Driver {
		return false
	}
	if this.ContainerDir != that1.ContainerDir {
		return false
	}
	if this.Mode != that1.Mode {
		return false
	}
	if !this.Shared.Equal(that1.Shared) {
		return false
	}
	return true
}
func (this *VolumePlacement) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*VolumePlacement)
	if !ok {
		that2, ok := that.(VolumePlacement)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.DriverNames) != len(that1.DriverNames) {
		return false
	}
	for i := range this.DriverNames {
		if this.DriverNames[i] != that1.DriverNames[i] {
			return false
		}
	}
	return true
}
func (this *SharedDevice) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&models.SharedDevice{")
	s = append(s, "VolumeId: "+fmt.Sprintf("%#v", this.VolumeId)+",\n")
	s = append(s, "MountConfig: "+fmt.Sprintf("%#v", this.MountConfig)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *VolumeMount) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&models.VolumeMount{")
	s = append(s, "DeprecatedVolumeId: "+fmt.Sprintf("%#v", this.DeprecatedVolumeId)+",\n")
	s = append(s, "DeprecatedMode: "+fmt.Sprintf("%#v", this.DeprecatedMode)+",\n")
	s = append(s, "DeprecatedConfig: "+fmt.Sprintf("%#v", this.DeprecatedConfig)+",\n")
	s = append(s, "Driver: "+fmt.Sprintf("%#v", this.Driver)+",\n")
	s = append(s, "ContainerDir: "+fmt.Sprintf("%#v", this.ContainerDir)+",\n")
	s = append(s, "Mode: "+fmt.Sprintf("%#v", this.Mode)+",\n")
	if this.Shared != nil {
		s = append(s, "Shared: "+fmt.Sprintf("%#v", this.Shared)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *VolumePlacement) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&models.VolumePlacement{")
	if this.DriverNames != nil {
		s = append(s, "DriverNames: "+fmt.Sprintf("%#v", this.DriverNames)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringVolumeMount(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringVolumeMount(m github_com_gogo_protobuf_proto.Message) string {
	e := github_com_gogo_protobuf_proto.GetUnsafeExtensionsMap(m)
	if e == nil {
		return "nil"
	}
	s := "proto.NewUnsafeXXX_InternalExtensions(map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "})"
	return s
}
func (m *SharedDevice) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *SharedDevice) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintVolumeMount(data, i, uint64(len(m.VolumeId)))
	i += copy(data[i:], m.VolumeId)
	data[i] = 0x12
	i++
	i = encodeVarintVolumeMount(data, i, uint64(len(m.MountConfig)))
	i += copy(data[i:], m.MountConfig)
	return i, nil
}

func (m *VolumeMount) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *VolumeMount) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintVolumeMount(data, i, uint64(len(m.Driver)))
	i += copy(data[i:], m.Driver)
	data[i] = 0x12
	i++
	i = encodeVarintVolumeMount(data, i, uint64(len(m.DeprecatedVolumeId)))
	i += copy(data[i:], m.DeprecatedVolumeId)
	data[i] = 0x1a
	i++
	i = encodeVarintVolumeMount(data, i, uint64(len(m.ContainerDir)))
	i += copy(data[i:], m.ContainerDir)
	data[i] = 0x20
	i++
	i = encodeVarintVolumeMount(data, i, uint64(m.DeprecatedMode))
	if m.DeprecatedConfig != nil {
		data[i] = 0x2a
		i++
		i = encodeVarintVolumeMount(data, i, uint64(len(m.DeprecatedConfig)))
		i += copy(data[i:], m.DeprecatedConfig)
	}
	data[i] = 0x32
	i++
	i = encodeVarintVolumeMount(data, i, uint64(len(m.Mode)))
	i += copy(data[i:], m.Mode)
	if m.Shared != nil {
		data[i] = 0x3a
		i++
		i = encodeVarintVolumeMount(data, i, uint64(m.Shared.Size()))
		n1, err := m.Shared.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *VolumePlacement) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *VolumePlacement) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.DriverNames) > 0 {
		for _, s := range m.DriverNames {
			data[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				data[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			data[i] = uint8(l)
			i++
			i += copy(data[i:], s)
		}
	}
	return i, nil
}

func encodeFixed64VolumeMount(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32VolumeMount(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintVolumeMount(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *SharedDevice) Size() (n int) {
	var l int
	_ = l
	l = len(m.VolumeId)
	n += 1 + l + sovVolumeMount(uint64(l))
	l = len(m.MountConfig)
	n += 1 + l + sovVolumeMount(uint64(l))
	return n
}

func (m *VolumeMount) Size() (n int) {
	var l int
	_ = l
	l = len(m.Driver)
	n += 1 + l + sovVolumeMount(uint64(l))
	l = len(m.DeprecatedVolumeId)
	n += 1 + l + sovVolumeMount(uint64(l))
	l = len(m.ContainerDir)
	n += 1 + l + sovVolumeMount(uint64(l))
	n += 1 + sovVolumeMount(uint64(m.DeprecatedMode))
	if m.DeprecatedConfig != nil {
		l = len(m.DeprecatedConfig)
		n += 1 + l + sovVolumeMount(uint64(l))
	}
	l = len(m.Mode)
	n += 1 + l + sovVolumeMount(uint64(l))
	if m.Shared != nil {
		l = m.Shared.Size()
		n += 1 + l + sovVolumeMount(uint64(l))
	}
	return n
}

func (m *VolumePlacement) Size() (n int) {
	var l int
	_ = l
	if len(m.DriverNames) > 0 {
		for _, s := range m.DriverNames {
			l = len(s)
			n += 1 + l + sovVolumeMount(uint64(l))
		}
	}
	return n
}

func sovVolumeMount(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozVolumeMount(x uint64) (n int) {
	return sovVolumeMount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *SharedDevice) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SharedDevice{`,
		`VolumeId:` + fmt.Sprintf("%v", this.VolumeId) + `,`,
		`MountConfig:` + fmt.Sprintf("%v", this.MountConfig) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VolumeMount) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VolumeMount{`,
		`Driver:` + fmt.Sprintf("%v", this.Driver) + `,`,
		`DeprecatedVolumeId:` + fmt.Sprintf("%v", this.DeprecatedVolumeId) + `,`,
		`ContainerDir:` + fmt.Sprintf("%v", this.ContainerDir) + `,`,
		`DeprecatedMode:` + fmt.Sprintf("%v", this.DeprecatedMode) + `,`,
		`DeprecatedConfig:` + fmt.Sprintf("%v", this.DeprecatedConfig) + `,`,
		`Mode:` + fmt.Sprintf("%v", this.Mode) + `,`,
		`Shared:` + strings.Replace(fmt.Sprintf("%v", this.Shared), "SharedDevice", "SharedDevice", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VolumePlacement) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VolumePlacement{`,
		`DriverNames:` + fmt.Sprintf("%v", this.DriverNames) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringVolumeMount(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *SharedDevice) Unmarshal(data []byte) error {
	var hasFields [1]uint64
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVolumeMount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SharedDevice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SharedDevice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VolumeId = string(data[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MountConfig", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MountConfig = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVolumeMount(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVolumeMount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("volume_id")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VolumeMount) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVolumeMount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VolumeMount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VolumeMount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Driver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Driver = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedVolumeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeprecatedVolumeId = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerDir", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerDir = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedMode", wireType)
			}
			m.DeprecatedMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.DeprecatedMode |= (DeprecatedBindMountMode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedConfig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeprecatedConfig = append(m.DeprecatedConfig[:0], data[iNdEx:postIndex]...)
			if m.DeprecatedConfig == nil {
				m.DeprecatedConfig = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shared", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Shared == nil {
				m.Shared = &SharedDevice{}
			}
			if err := m.Shared.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVolumeMount(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVolumeMount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VolumePlacement) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVolumeMount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VolumePlacement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VolumePlacement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DriverNames", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolumeMount
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DriverNames = append(m.DriverNames, string(data[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVolumeMount(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVolumeMount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVolumeMount(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVolumeMount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVolumeMount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthVolumeMount
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowVolumeMount
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipVolumeMount(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthVolumeMount = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVolumeMount   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("volume_mount.proto", fileDescriptorVolumeMount) }

var fileDescriptorVolumeMount = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0x62, 0xe8, 0xc4, 0xa4, 0xe9, 0x2a, 0x08, 0x8b, 0x43, 0x12, 0xe5, 0x80, 0x00,
	0x15, 0x57, 0x6a, 0x0f, 0x20, 0x8e, 0x21, 0x42, 0xe2, 0x50, 0xa8, 0x16, 0xa9, 0x1c, 0x2d, 0xd7,
	0xbb, 0x4d, 0x57, 0x8a, 0xbd, 0xd5, 0xc6, 0x09, 0x57, 0xc4, 0x17, 0xf0, 0x19, 0x7c, 0x4a, 0x8f,
	0x3d, 0x72, 0xaa, 0x68, 0xb9, 0x20, 0x4e, 0x7c, 0x02, 0xe3, 0xd9, 0xad, 0xed, 0x1e, 0x7a, 0x18,
	0x8f, 0x67, 0xde, 0xbc, 0x99, 0xb7, 0x33, 0xc0, 0xd6, 0x7a, 0xb1, 0xca, 0x64, 0x9c, 0xe9, 0x55,
	0x5e, 0x44, 0x67, 0x46, 0x17, 0x9a, 0xf9, 0x99, 0x16, 0x72, 0xb1, 0x7c, 0xf2, 0x72, 0xae, 0x8a,
	0xd3, 0xd5, 0x71, 0x94, 0xea, 0x6c, 0x77, 0xae, 0xe7, 0x7a, 0x97, 0xe0, 0xe3, 0xd5, 0x09, 0x45,
	0x14, 0xd0, 0x9f, 0xa5, 0x4d, 0xbe, 0x40, 0xf0, 0xe9, 0x34, 0x31, 0x52, 0xcc, 0xe4, 0x5a, 0xa5,
	0x92, 0x45, 0xb0, 0xe9, 0x9a, 0x2b, 0x11, 0x7a, 0xe3, 0xf6, 0xb3, 0xcd, 0xe9, 0xf6, 0xf9, 0xe5,
	0xa8, 0xf5, 0xf7, 0x72, 0x54, 0x03, 0xfc, 0x81, 0xfd, 0x7d, 0x2f, 0xd8, 0x2b, 0x08, 0x48, 0x45,
	0x9c, 0xea, 0xfc, 0x44, 0xcd, 0xc3, 0xf6, 0xd8, 0x43, 0xca, 0xc0, 0x51, 0x6e, 0x61, 0xbc, 0x4b,
	0xd1, 0x5b, 0x0a, 0x26, 0xdf, 0x3a, 0xd0, 0x3d, 0xa2, 0x2e, 0x07, 0x65, 0x96, 0x3d, 0x05, 0x5f,
	0x18, 0xb5, 0x96, 0x06, 0xa7, 0x96, 0x2d, 0x7a, 0xae, 0x85, 0xcb, 0x72, 0xe7, 0xd9, 0x6b, 0x18,
	0x08, 0x79, 0x66, 0x64, 0x9a, 0x14, 0x52, 0xc4, 0xb5, 0x56, 0x3b, 0xd8, 0x2f, 0x59, 0xa1, 0xc7,
	0x59, 0x5d, 0x73, 0x74, 0x23, 0xf5, 0x0d, 0x3c, 0x44, 0x21, 0x45, 0xa2, 0x72, 0x69, 0x62, 0xa1,
	0x4c, 0xd8, 0x21, 0xca, 0x23, 0x37, 0xe8, 0x36, 0xc8, 0x83, 0x2a, 0x9c, 0x29, 0xc3, 0x0e, 0x61,
	0xab, 0x31, 0xb5, 0x5c, 0x75, 0xb8, 0x81, 0xec, 0xde, 0xde, 0x28, 0xb2, 0x7b, 0x8f, 0x66, 0x15,
	0x3c, 0x55, 0xb9, 0xa0, 0x37, 0x1d, 0x20, 0x52, 0x29, 0xea, 0xd5, 0xfc, 0x32, 0xcf, 0xf6, 0x61,
	0xbb, 0xd1, 0xd1, 0x6d, 0xef, 0x1e, 0xf6, 0x0c, 0x2a, 0x4a, 0xbf, 0x2e, 0xb0, 0x4b, 0x63, 0x63,
	0xd8, 0xa0, 0xd9, 0x3e, 0x29, 0x0f, 0x9c, 0x72, 0xca, 0x71, 0xfa, 0xb2, 0x1d, 0xf0, 0x97, 0x74,
	0xcf, 0xf0, 0x3e, 0xd6, 0x74, 0xf7, 0x06, 0x37, 0xfa, 0x9a, 0x57, 0xe6, 0xae, 0x66, 0xf2, 0x0e,
	0xb6, 0xec, 0x7a, 0x0e, 0x17, 0x49, 0x2a, 0x33, 0x89, 0x77, 0xd8, 0x87, 0xc0, 0x6e, 0x3a, 0xce,
	0x93, 0x4c, 0x2e, 0xf1, 0x1a, 0x1d, 0x1c, 0xd5, 0x2f, 0x8f, 0xd9, 0xcc, 0xf3, 0xae, 0x8d, 0x3e,
	0x94, 0xc1, 0x8b, 0xe7, 0xf0, 0xf8, 0x8e, 0xf7, 0x33, 0x1f, 0xda, 0xfc, 0x63, 0xbf, 0x45, 0xfe,
	0x73, 0xdf, 0x9b, 0xee, 0x5c, 0x5c, 0x0d, 0xbd, 0x9f, 0x57, 0xc3, 0xd6, 0x3f, 0xf4, 0x5f, 0xaf,
	0x87, 0xde, 0x0f, 0xb4, 0x73, 0xb4, 0x0b, 0xb4, 0x5f, 0x68, 0x7f, 0xae, 0x11, 0x43, 0xff, 0xfd,
	0xf7, 0xb0, 0xf5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x17, 0xbc, 0x1f, 0xea, 0x02, 0x00, 0x00,
}
